// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDownloads(arg1:Array<string>,arg2:string):Promise<Array<main.DownloadItem>>;

export function AddVideoDownloads(arg1:Array<main.VideoDownloadRequest>):Promise<Array<main.DownloadItem>>;

export function CancelAll():Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function ClearAll():Promise<void>;

export function ClearCompleted():Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetDownloads():Promise<Array<main.DownloadItem>>;

export function GetPlaylistInfo(arg1:string):Promise<main.PlaylistInfo>;

export function GetStats():Promise<main.QueueStats>;

export function GetVideoFormats(arg1:string):Promise<main.VideoInfo>;

export function OpenDirectory(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function PauseQueue():Promise<void>;

export function ResumeQueue():Promise<void>;

export function RetryDownload(arg1:string):Promise<main.DownloadItem>;

export function RetryFailed():Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<main.Config>;

export function SelectFolder():Promise<string>;

export function SetLanguage(arg1:string):Promise<void>;
