// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownloads(arg1, arg2) {
  return window['go']['main']['App']['AddDownloads'](arg1, arg2);
}

export function AddVideoDownloads(arg1) {
  return window['go']['main']['App']['AddVideoDownloads'](arg1);
}

export function CancelAll() {
  return window['go']['main']['App']['CancelAll']();
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function ClearAll() {
  return window['go']['main']['App']['ClearAll']();
}

export function ClearCompleted() {
  return window['go']['main']['App']['ClearCompleted']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDownloads() {
  return window['go']['main']['App']['GetDownloads']();
}

export function GetPlaylistInfo(arg1) {
  return window['go']['main']['App']['GetPlaylistInfo'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetVideoFormats(arg1) {
  return window['go']['main']['App']['GetVideoFormats'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PauseQueue() {
  return window['go']['main']['App']['PauseQueue']();
}

export function ResumeQueue() {
  return window['go']['main']['App']['ResumeQueue']();
}

export function RetryDownload(arg1) {
  return window['go']['main']['App']['RetryDownload'](arg1);
}

export function RetryFailed() {
  return window['go']['main']['App']['RetryFailed']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}
